services:
  - type: web
    name: news-aggregator-backend
    env: node
    region: oregon
    plan: free
    buildCommand: npm install
    startCommand: node src/index.js
    rootDir: .
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: HUGGINGFACE_API_KEY
        sync: false
    healthCheckPath: /health
    autoDeploy: true 